# Security
minimumReleaseAge: 14400 # 10 days (expressed in minutes)
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: false
minimumReleaseAgeExclude: []
strictDepBuilds: true
allowBuilds: {}
blockExoticSubdeps: true
trustPolicy: no-downgrade
trustPolicyExclude: []
auditConfig:
  ignoreGhsas: []

# Package manager/version safety
engineStrict: true
pmOnFail: download
verifyDepsBeforeRun: error
